/**
 * Concept lexicon (spec §4.1). Every phrase is written in STANDARD Vietnamese; dialect words are
 * rewritten before tagging (lexicon/dialect.ts). A few dialect forms that cannot be rewritten in
 * no-diacritics input are listed here directly (e.g. "làm được chi").
 *
 * Phrase DSL: tokens separated by spaces · `a|b` token alternatives · `[x]` optional token ·
 * `#` = one number (a whole run such as "hai mươi mốt"). Phrases are canonicalized at load time.
 */

export interface PhraseSpec {
  p: string
  /** Multiplies the span score (default 1). */
  weight?: number
  /** Subtracted from the score when the whole input has no diacritics. */
  asciiPenalty?: number
}
export type PhraseDef = string | PhraseSpec

/** Who a reminder / invitation is for: every way users refer to themselves (tau/mệ are rewritten). */
const ME = 'tôi|mình|tui|tớ|tao|con|cháu|em|bà|ông|mẹ|bố|ba|má|cô|chú|bác|anh|chị'

export const CONCEPTS = {
  // ---------------------------------------------------------------- motion
  JUMP: [
    'nhảy',
    'nhảy lên',
    'nhảy cao',
    'bật nhảy',
    'nhảy tưng tưng',
    'nhảy lò cò',
    'nhún',
    'nhảy tại chỗ',
    'nhảy nhảy',
    'nhảy cao lên',
  ],
  DANCE: [
    'nhảy múa',
    'múa',
    'múa may',
    'nhảy đầm',
    'nhảy nhót',
    'nhún nhảy',
    'nhảy # bài',
    'múa # bài',
    'nhảy điệu',
    'nhảy theo nhạc',
    'khiêu vũ',
    'quẩy',
    'quẩy lên',
    'đi quẩy',
    'lắc lư',
    'lắc hông',
    'lắc mông',
    'biểu diễn',
    'nhảy disco',
    'nhảy hip hop',
    `nhảy với ${ME}`,
    `chơi với ${ME}`,
    'dance',
    'nhảy nhạc',
    'nhảy một điệu',
  ],
  // (no clapping clip: "vỗ tay" waves both hands' worth of joy)
  WAVE: [
    'vẫy tay',
    'vẫy',
    'vẫy vẫy',
    'vẫy chào',
    'vẫy tay chào',
    'giơ tay chào',
    'giơ tay',
    'đưa tay',
    'vẫy vẫy tay',
    'vỗ tay',
  ],
  NOD: ['gật đầu', 'gật', 'gật gù', 'gật gật', 'gục gặc [đầu]', 'gật gật đầu'],
  SHAKE: ['lắc đầu', 'lắc', 'lắc lắc đầu', 'lắc đầu quầy quậy', 'lắc đầu nguầy nguậy', 'lắc lắc'],
  // critique fix: no bare 'lai' (collides with "lại" in no-diacritics input)
  THUMB: ['giơ ngón [tay] cái', 'ngón [tay] cái', 'like', 'bấm|chấm|thả like', 'giơ ngón cái lên'],
  PUNCH: [
    'đấm',
    'đấm bốc',
    'đấm đá',
    'tung cú đấm',
    'ra đòn',
    'đánh võ',
    'múa võ',
    'boxing',
    'đấm vào không khí',
    { p: 'đánh', weight: 0.8 },
  ],
  WALK: [
    'đi',
    'đi bộ',
    'bước',
    'bước đi',
    'tiến',
    'tiến lên|tới',
    'đi tới',
    'đi thẳng',
    'đi lên',
    'đi dạo',
    'dạo',
    'đi chơi',
    'đi vòng quanh',
    'đi qua đi lại',
    'đi tới trước',
    'đi về phía trước',
    'đi thẳng về phía trước',
    'bước tới',
    'đi loanh quanh',
    'đi tiếp',
  ],
  WALK_USER: [
    'lại đây',
    'đến|tới|ra|qua|vô|vào đây',
    'đi lại đây',
    'đi vào|vô|đến|tới|ra|qua đây',
    'lại gần [đây]',
    'đến|tới gần [đây]',
    'đi lại gần',
    `đến với ${ME}`,
    'về đây',
    `lại với ${ME}`,
  ],
  WALK_HOME: [
    'về chỗ cũ',
    'về chỗ',
    'về vị trí cũ',
    'về vị trí',
    'quay về chỗ cũ',
    'trở về chỗ cũ',
    'về chỗ ban đầu',
    'đi về chỗ cũ',
    'quay về',
    'trở về',
    'đi về',
    'về giữa',
    'về chỗ của bạn',
    'về nhà',
    'đi về nhà',
  ],
  BACK: [
    'lùi',
    'lùi lại',
    'đi lùi',
    'bước lùi',
    'lui',
    'lui lại',
    'đi lui',
    'lùi về sau',
    'đi ra sau',
    'ra xa',
    'đi ra xa',
    'tránh ra',
    'đi chỗ khác',
    'lùi ra',
    'lùi xa',
    'lùi về phía sau',
    'đi|lùi|bước ra|về phía sau',
    'đi|bước về sau',
    'bước lui',
    'lui về sau',
    'thụt lùi',
    'đi thụt lùi',
  ],
  RUN: [
    'chạy',
    'chạy bộ',
    'chạy nhanh',
    'chạy tại chỗ',
    'chạy vòng vòng',
    'chạy vòng quanh',
    'chạy thể dục',
    'chạy đi chạy lại',
  ],
  TURN: ['quay', 'xoay', 'rẽ', 'ngoảnh', 'quay người', 'xoay người', 'nhìn', 'quay mặt', 'xoay mặt', 'hướng'],
  LEFT: ['trái', 'bên trái', 'sang|qua|phía|về|hướng bên trái', 'sang|qua|phía|về|hướng trái', 'tay trái'],
  RIGHT: ['phải', 'bên phải', 'sang|qua|phía|về|hướng bên phải', 'sang|qua|phía|về|hướng phải', 'tay phải'],
  AROUND: [
    'quay lại',
    'quay đầu',
    'quay lưng [lại]',
    'quay mặt lại',
    'quay ra sau',
    'phía sau',
    'đằng sau',
    'xoay lại',
    'quay đằng sau',
    'quay ngược lại',
    'đằng sau quay',
    'quay ra phía sau',
    'xoay ra sau',
    'ngoảnh lại',
    'quay về phía sau',
    'nửa vòng',
    'quay nửa vòng',
  ],
  SPIN: [
    '# vòng',
    'vòng tròn',
    'xoay vòng',
    'quay vòng',
    'quay mòng mòng',
    'xoay mòng mòng',
    'xoay tròn',
    'quay tròn',
    'quay # vòng',
    'xoay # vòng',
    'xoay vòng vòng',
    'quay vòng vòng',
    'quay vòng tròn',
    'xoay vòng tròn',
  ],
  SIT: [
    'ngồi',
    'ngồi xuống',
    'ngồi nghỉ',
    'ngồi yên',
    'ngồi bệt',
    'nghỉ ngơi',
    'nghỉ chân',
    'ngồi xuống đây',
  ],
  STAND: ['đứng', 'đứng lên', 'đứng dậy', 'đứng thẳng [lên]', 'đứng dậy đi'],
  // critique fix: no 'tắt máy' (collides with OFF + device nouns)
  SLEEP: [
    'ngủ',
    'đi ngủ',
    'ngủ trưa',
    'ngủ ngon',
    'chúc ngủ ngon',
    'ngủ # giấc',
    'nhắm mắt',
    'buồn ngủ',
    'đi nghỉ',
    'ngủ đi',
    'ngủ một chút',
  ],
  WAKE: [
    'dậy',
    'thức dậy',
    'tỉnh dậy',
    'thức',
    // (no bare "tỉnh": "thời tiết tỉnh Nghệ An" is a province)
    'tỉnh lại',
    'mở mắt',
    'ngồi dậy',
    'dậy thôi',
    'dậy đi',
    'thức giấc',
  ],
  FALL: [
    'ngã',
    'té',
    'té ngã',
    'ngã xuống',
    'giả chết',
    'giả vờ ngã',
    'giả vờ chết',
    'nằm',
    'nằm xuống',
    'nằm ra',
    'lăn ra',
    'ngã ra',
    'ngã lăn ra',
    'nằm ngửa',
    'té xuống',
    'chết',
    'ngã ngửa',
  ],
  STOP: [
    'dừng',
    'dừng lại',
    'ngừng',
    'ngưng',
    'ngừng lại',
    'ngưng lại',
    'đứng lại',
    'đứng yên',
    'đứng im',
    'stop',
    'đủ rồi',
    'thôi',
    'dừng tay',
    'thôi đủ rồi',
    'dừng ngay',
    { p: 'được rồi', weight: 0.6 },
  ],
  SAD: ['buồn', 'làm mặt buồn', 'mặt buồn', 'khóc', 'mếu', 'tủi thân', 'buồn bã'],
  ANGRY: [
    'giận',
    'tức giận',
    'nổi giận',
    'cáu',
    'nổi cáu',
    'tức',
    'bực',
    'bực mình',
    'làm mặt giận',
    'mặt giận',
    'giận dữ',
  ],
  SURPRISE: [
    'ngạc nhiên',
    'bất ngờ',
    'hết hồn',
    'giật mình',
    'sốc',
    'hú hồn',
    'ngỡ ngàng',
    'làm mặt ngạc nhiên',
    'mặt ngạc nhiên',
  ],
  HAPPY: [
    'vui',
    'vui lên',
    'vui vẻ',
    'cười',
    'cười lên',
    'mỉm cười',
    'hạnh phúc',
    'tươi lên',
    'làm mặt vui',
    'mặt vui',
    'cười tươi',
  ],
  /**
   * A possible real emergency: never a gag. The robot says it cannot call for help and points to
   * 115 / family (a user who fell is also routed here, see resolve.ts FALL).
   */
  EMERGENCY: [
    'cứu',
    'cứu với',
    `cứu ${ME} [với]`,
    'cứu mạng',
    'cấp cứu',
    'gọi cấp cứu',
    'gọi xe cấp cứu',
    'khó thở',
    'đau ngực',
    'tức ngực',
    'đau tim',
    'lên cơn đau tim',
    'đột quỵ',
    'cháy nhà',
    'có cháy',
    'cháy rồi',
    'bị ngất',
    'ngất xỉu',
  ],
  /** Only ever about the user ("tôi mệt quá"). */
  TIRED: ['mệt', 'mệt quá', 'mệt mỏi', 'đuối', 'mệt lắm'],

  // ---------------------------------------------------------------- information
  TIME: [
    'mấy giờ',
    'mấy giờ rồi',
    'bao nhiêu giờ',
    'xem giờ',
    'giờ giấc',
    'thời gian',
    'giờ hiện tại',
    'bây giờ là mấy giờ',
    'giờ là mấy giờ',
    'giờ mấy',
    'mấy giờ bây giờ',
  ],
  DATE: [
    'ngày mấy',
    'ngày bao nhiêu',
    'ngày tháng',
    'tháng mấy',
    'năm bao nhiêu',
    'ngày giờ',
    'xem lịch',
    'là ngày nào',
    'ngày gì',
    'ngày tháng năm',
  ],
  WEEKDAY: ['thứ mấy', 'thứ gì', 'là thứ', 'thứ bao nhiêu'],
  LUNAR: [
    'âm lịch',
    'lịch âm',
    'ngày âm [lịch]',
    'ngày ta',
    'lịch ta',
    'tháng ta',
    'mùng mấy',
    'lịch âm dương',
  ],
  LUNAR_YEAR: [
    'năm con gì',
    'con giáp',
    'can chi',
    'năm gì',
    'tuổi con gì',
    'năm con chi',
    'năm con giáp gì',
  ],
  TET: ['tết', 'tết nguyên đán', 'tết âm lịch', 'tết ta'],
  RAM: ['rằm', 'ngày rằm', 'trăng tròn'],
  /** Lunar festivals answered as a rằm of their month (see resolve.ts festivalMonth). */
  FESTIVAL: [
    'trung thu',
    'tết trung thu',
    'rằm trung thu',
    'vu lan',
    'lễ vu lan',
    'tết nguyên tiêu',
    'nguyên tiêu',
  ],
  MUNG1: ['mùng #'],
  HOWLONG: [
    'bao lâu',
    'bao nhiêu ngày',
    'mấy ngày',
    'khi nào',
    'bao giờ',
    'ngày nào',
    'hôm nào',
    'lúc nào',
    'còn bao nhiêu ngày',
    'còn mấy ngày',
  ],
  TIMER: [
    'hẹn giờ',
    'đặt [hẹn] giờ',
    'đếm ngược',
    'bấm giờ',
    'canh giờ',
    '[đặt] báo thức',
    'đồng hồ hẹn giờ',
    { p: 'hẹn', weight: 0.7 },
  ],
  REMIND: ['nhắc', `nhắc ${ME}`, 'nhắc nhở', `báo ${ME}`, `kêu ${ME}`, 'nhắc giùm'],
  /** "đánh thức tôi", "gọi / kêu tui dậy": a reminder labelled "thức dậy" (never punch + wake). */
  WAKE_ME: ['đánh thức', `đánh thức ${ME}`, `đánh thức ${ME} dậy`, `gọi|kêu ${ME} dậy`, 'gọi|kêu dậy'],
  // "dẹp" = Southern "cancel"
  CANCEL: ['hủy', 'hủy bỏ', 'bỏ', 'xóa', 'dẹp'],
  STATUS: [
    'còn bao lâu',
    'còn mấy phút|giây',
    'còn bao nhiêu phút|giây',
    'còn bao nhiêu thời gian',
    'hẹn giờ còn bao lâu',
  ],
  WEATHER: [
    'thời tiết',
    'dự báo [thời tiết]',
    'nhiệt độ',
    'bao nhiêu độ',
    'mấy độ',
    'độ ẩm',
    'khí hậu',
    { p: 'trời', weight: 0.7 },
    { p: 'gió', weight: 0.6 },
  ],
  RAIN: ['mưa', 'có mưa', 'trời mưa', 'mang ô|dù', 'mang áo mưa', 'áo mưa', 'có mưa to'],
  HOTCOLD: ['nóng', 'lạnh', 'rét', 'oi', 'mát', 'có nóng', 'có lạnh'],
  SUNNY: ['nắng', 'có nắng', 'trời nắng'],

  // ---------------------------------------------------------------- conversation
  GREET: [
    'xin chào',
    'chào',
    'chào bạn|robot|cháu|con|em|ronaldo|anh|chị',
    'hello',
    'hi',
    'alo',
    'chào buổi sáng|trưa|chiều|tối',
    'chào cả nhà',
    'chào mọi người',
    'xin chào bạn',
  ],
  THANKS: ['cảm ơn', 'cảm ơn nhiều', 'cảm ơn bạn', 'thank you', 'thanks', 'thank', 'tks', 'đa tạ'],
  BYE: [
    'tạm biệt',
    'chào tạm biệt',
    'bái bai',
    'bye',
    'bye bye',
    'bai bai',
    'hẹn gặp lại',
    'gặp lại sau',
    'goodbye',
  ],
  PRAISE: [
    'giỏi',
    'giỏi quá',
    'giỏi lắm',
    'hay quá',
    'hay lắm',
    'tuyệt',
    'tuyệt vời',
    'đỉnh',
    'xịn',
    'ngoan',
    'dễ thương',
    'đáng yêu',
    'đẹp trai',
    'được lắm',
    'khá lắm',
    'số dách',
    'số dzách',
    'hết sẩy',
    'quá đã',
    'buồn cười',
    // Southern "tức cười", "mắc cười" = so funny
    'tức cười',
    'mắc cười',
    'hài quá',
    'good',
    'thông minh',
    'đẹp quá',
  ],
  INSULT: [
    { p: 'ngu', asciiPenalty: 0.1 },
    'ngốc',
    'đồ ngốc',
    'đồ ngu',
    'ngu ngốc',
    'dốt',
    'dở',
    'dở ẹc',
    'dở tệ',
    'tệ',
    'kém',
    'xấu xí',
  ],
  WHO: [
    'bạn là ai',
    'mày là ai',
    'cậu là ai',
    'là ai',
    'tên gì',
    'tên là gì',
    'tên bạn',
    'giới thiệu [bản thân]',
    'bạn là gì',
    'giới thiệu về bạn',
  ],
  CREATOR: [
    'ai tạo ra',
    'ai làm ra',
    'ai chế tạo',
    'ai lập trình',
    'ai sinh ra',
    'ai tạo',
    'ai làm ra bạn',
    'ai tạo nên',
  ],
  AGE: ['bao nhiêu tuổi', 'mấy tuổi'],
  PROJECT: [
    'mô hình',
    'phowhisper',
    'pho whisper',
    'whisper',
    'qwen',
    'wer',
    'độ chính xác',
    'nghiên cứu',
    'dự án',
    'đề tài',
    'vimd',
    'nhận dạng|nhận diện giọng nói',
  ],
  HOWRU: [
    'khỏe không',
    'có khỏe không',
    'khỏe chứ',
    'thế nào rồi',
    'dạo này thế nào',
    'dạo này sao [rồi]',
    `dạo này ${ME} thế nào|sao`,
    `dạo này ${ME} khỏe không`,
    'dạo này khỏe không',
    'ổn không',
    'có ổn không',
    'khỏe không vậy',
  ],
  CAPS: [
    'làm được gì',
    'làm được những gì',
    'biết làm gì',
    'biết làm những gì',
    'có thể làm gì',
    'có thể làm những gì',
    'làm gì được',
    'giúp gì được',
    'biết gì',
    'trợ giúp',
    'hướng dẫn',
    'help',
    'tính năng',
    'chức năng',
    // dialect duplicates for no-diacritics input (chi → gì is accented-only)
    'làm được chi',
    'biết làm chi',
    'làm chi được',
  ],
  JOKE: [
    'kể chuyện cười',
    'chuyện cười',
    'chuyện vui',
    'truyện cười',
    'kể truyện cười',
    'kể chuyện',
    'kể gì vui',
    'nói gì vui',
    'chọc cười',
    `làm ${ME} cười`,
    `chọc ${ME} cười`,
    'đố vui',
    'câu đố',
    'joke',
    'tấu hài',
    'pha trò',
    'đùa',
    'giỡn',
    'kể chuyện tiếu lâm',
    'chuyện tiếu lâm',
  ],
  LOVE: ['yêu|thương|quý|thích bạn|robot|mày|cậu|em|tôi|tui|mình'],
  REPEAT: ['lại', 'làm lại', 'lặp lại', 'nữa', 'tiếp', 'tiếp tục', 'làm tiếp', 'làm lại đi'],
  MUTE: [
    'im lặng',
    'im đi',
    'im',
    'đừng nói [nữa]',
    'tắt tiếng',
    'tắt âm thanh',
    'tắt loa',
    'tắt giọng',
    'tắt tiếng nói',
    'câm',
  ],
  UNMUTE: ['bật|mở tiếng', 'bật|mở âm thanh', 'bật|mở loa', 'nói to lên', 'lên tiếng', 'bật|mở giọng'],
  SPEAK: ['nói', 'đổi sang', 'chuyển sang', 'dùng', 'nói bằng'],
  LANG_EN: ['tiếng anh', 'english', 'anh ngữ'],
  LANG_VI: ['tiếng việt', 'vietnamese'],

  // ---------------------------------------------------------------- simulated smart home
  ON: [
    'bật',
    'mở',
    'bật lên',
    'mở lên',
    'thắp',
    'thắp sáng',
    'cho sáng',
    'làm sáng',
    'khởi động',
    'sáng lên',
    'bật sáng',
    'bật|mở hết',
  ],
  OFF: ['tắt', 'tắt đi', 'tắt hết', 'sập', 'cho tắt', 'ngắt', 'tắt luôn'],
  CLOSE: ['đóng', 'đóng lại'],
  LIGHT: [
    'đèn',
    'bóng đèn',
    'đèn điện',
    'đèn phòng',
    'đèn trần',
    'đèn ngủ',
    'đèn bàn',
    'ánh sáng',
    'cây đèn',
    'cái đèn',
    { p: 'điện', weight: 0.7 },
  ],
  FAN: ['quạt', 'quạt máy', 'quạt điện', 'quạt trần', 'quạt gió', 'quạt đứng', 'cái quạt', 'cây quạt'],
  COLOR_KW: [
    'màu',
    'đổi màu',
    'chuyển màu',
    'thành màu',
    'sang màu',
    'màu sắc',
    'đổi sang',
    { p: 'đổi|chuyển', weight: 0.5 },
  ],
  FAN_SPEED: ['số #', 'tốc độ #', 'mức #', 'nấc #'],
  SPEED_UP: [
    'mạnh lên',
    'mạnh hơn',
    'mạnh thêm',
    'to lên',
    'tăng',
    'tăng lên',
    'tăng tốc',
    'tăng số',
    'nhanh hơn',
    'lớn lên',
    'chạy nhanh hơn|lên',
    'chạy mạnh hơn|lên',
  ],
  SPEED_DOWN: [
    'nhẹ lại',
    'nhẹ hơn',
    'nhẹ bớt',
    'yếu lại',
    'nhỏ lại',
    'giảm',
    'giảm xuống',
    'giảm số',
    'chậm lại',
    'chậm hơn',
    'êm lại',
    'chạy chậm lại|hơn',
    'chạy nhẹ lại|hơn',
  ],
  IMPL_DARK: ['tối quá', 'tối thui', 'tối om', 'không thấy gì', 'tối thế', 'hơi tối', 'tối lắm'],
  IMPL_HOT: ['nóng quá', 'nóng nực', 'oi quá', 'oi bức', 'nóng thế', 'hơi nóng', 'nóng lắm', 'nóng chết'],
  IMPL_COLD: ['lạnh quá', 'rét quá', 'lạnh thế', 'hơi lạnh', 'lạnh lắm'],

  // ---------------------------------------------------------------- operators on meaning
  NEG: [
    'đừng',
    'đừng có',
    'không',
    'chớ',
    'khỏi',
    'không cần',
    'không được',
    'chẳng',
    'chả',
    'cấm',
    'thôi đừng',
    'không nên',
    'khỏi cần',
    // "coi chừng té" / "cẩn thận ngã" warn against it
    'coi chừng',
    'cẩn thận',
  ],
  QMARK: [
    'không',
    'chưa',
    'hả',
    'sao',
    'thế nào',
    'ra sao',
    'như thế nào',
    'gì',
    'mấy',
    'bao nhiêu',
    'thế nào vậy',
  ],
} as const satisfies Record<string, readonly PhraseDef[]>

export type LexConcept = keyof typeof CONCEPTS
