import type { DialectRegion, SubstitutionKind } from '@/core/parser'

/**
 * Dialect and spelling rewrites (spec §2 N8 and §3), applied left to right before tagging.
 * Classes: `ascii: true` entries also apply to no-diacritics tokens; the others ("ACC") apply only
 * when the input is typed with diacritics, because their stripped forms collide with other words.
 *
 * Linguistic lists come from knowledge, not a corpus: team members from Central and Southern
 * provinces should review the exception lists.
 */
export interface RewriteEntry {
  /** Source tokens (standard lowercase, any tone style; canonicalized at load). */
  from: string
  /** Replacement tokens. */
  to: string
  kind: SubstitutionKind
  region?: readonly DialectRegion[]
  ascii?: boolean
  skipIfPrev?: readonly string[]
  skipIfNext?: readonly string[]
  /** '' stands for "no token" (start / end of the sentence). */
  onlyIfPrev?: readonly string[]
  onlyIfNext?: readonly string[]
  /** Only as the last word (trailing particles do not count). */
  onlyLast?: boolean
  /** Never as the last word. */
  notLast?: boolean
  /** Skip a capitalized word that is not sentence-initial (a proper name). */
  skipIfCapitalized?: boolean
  /** Use `to` = altTo after one of these words. */
  altAfterPrev?: { prev: readonly string[]; to: string }
}

const C = 'central' as const
const H = 'hue' as const
const Q = 'quang' as const
const NT = 'ngheTinh' as const
const S = 'southern' as const

/** Chat abbreviations and common misspellings (all ASCII-safe unless marked). */
export const SPELLING: readonly RewriteEntry[] = [
  ...['ko', 'k', 'kh', 'khg', 'hok', 'hk', 'khum', 'kg'].map((f): RewriteEntry => ({
    from: f,
    to: 'không',
    kind: 'chat',
    ascii: true,
  })),
  ...['dc', 'đc', 'dk', 'đk'].map((f): RewriteEntry => ({ from: f, to: 'được', kind: 'chat', ascii: true })),
  { from: 'j', to: 'gì', kind: 'chat', ascii: true },
  { from: 'r', to: 'rồi', kind: 'chat', ascii: true },
  // chat "h" for giờ ("mấy h rồi", "bây h"); after digits it is rewritten before tokenizing
  { from: 'h', to: 'giờ', kind: 'chat', ascii: true, onlyIfPrev: ['mấy', 'bây', 'nhiêu'] },
  { from: 'vs', to: 'với', kind: 'chat', ascii: true },
  { from: 'bn', to: 'bạn', kind: 'chat', ascii: true },
  { from: 'bnh', to: 'bao nhiêu', kind: 'chat', ascii: true },
  { from: 'bnhiu', to: 'bao nhiêu', kind: 'chat', ascii: true },
  { from: 'ntn', to: 'như thế nào', kind: 'chat', ascii: true },
  { from: 'rùi', to: 'rồi', kind: 'spelling' },
  { from: 'wá', to: 'quá', kind: 'spelling' },
  { from: 'z', to: 'vậy', kind: 'chat', ascii: true },
  ...['oke', 'okie', 'oki', 'okê', 'oce', 'okay', 'ô kê'].map((f): RewriteEntry => ({
    from: f,
    to: 'ok',
    kind: 'chat',
    ascii: true,
  })),
  { from: 'cám ơn', to: 'cảm ơn', kind: 'spelling' },
  { from: 'nhẩy', to: 'nhảy', kind: 'spelling' },
  { from: 'bẩy', to: 'bảy', kind: 'spelling' },
  { from: 'ngàn', to: 'nghìn', kind: 'spelling' },
  ...['rô bốt', 'rôbốt', 'robo', 'rô bô'].map((f): RewriteEntry => ({
    from: f,
    to: 'robot',
    kind: 'spelling',
  })),
  { from: 'ti vi', to: 'tivi', kind: 'spelling', ascii: true },
  { from: 'tv', to: 'tivi', kind: 'chat', ascii: true },
  { from: 'helo', to: 'hello', kind: 'spelling', ascii: true },
  { from: 'hế lô', to: 'hello', kind: 'spelling' },
  { from: 'mồng', to: 'mùng', kind: 'spelling' },
  { from: 'tphcm', to: 'tp hcm', kind: 'chat', ascii: true },
]

/** Regional words → standard words (spec §3, with the critique's corrections). */
export const DIALECT: readonly RewriteEntry[] = [
  // ---- bigrams first (the engine tries longer entries first anyway)
  { from: 'bây chừ', to: 'bây giờ', kind: 'dialect', region: [C, H, Q] },
  { from: 'bi chừ', to: 'bây giờ', kind: 'dialect', region: [C] },
  { from: 'bi giờ', to: 'bây giờ', kind: 'dialect', region: [S], ascii: true },
  { from: 'mần ơn', to: 'làm ơn', kind: 'dialect', region: [S, NT] },
  { from: 'bữa nay', to: 'hôm nay', kind: 'dialect', region: [S], ascii: true },
  { from: 'bữa ni', to: 'hôm nay', kind: 'dialect', region: [C, H, NT], ascii: true },
  { from: 'hôm ni', to: 'hôm nay', kind: 'dialect', region: [C, H, NT], ascii: true },
  { from: 'ngày ni', to: 'hôm nay', kind: 'dialect', region: [C, H, NT], ascii: true },
  // critique: "bựa ni" (Nghệ Tĩnh "today") was missing
  { from: 'bựa ni', to: 'hôm nay', kind: 'dialect', region: [NT], ascii: true },
  { from: 'bữa qua', to: 'hôm qua', kind: 'dialect', region: [S], ascii: true },
  {
    from: 'quá trời',
    to: 'quá',
    kind: 'dialect',
    region: [S],
    ascii: true,
    skipIfPrev: ['bữa', 'bựa', 'hôm', 'ngày', 'sáng', 'chiều', 'tối'],
  },
  { from: 'quá xá', to: 'quá', kind: 'dialect', region: [S], ascii: true },
  { from: 'dữ thần', to: 'quá', kind: 'dialect', region: [S] },
  // Nghệ Tĩnh "bựa qua" = hôm qua; "quá trời" after a day word is not "very"
  { from: 'bựa qua', to: 'hôm qua', kind: 'dialect', region: [NT], ascii: true },
  { from: 'bựa trước', to: 'hôm trước', kind: 'dialect', region: [NT] },
  // no-diacritics Central words, only where the context rules out the look-alike
  { from: 'bây chừ', to: 'bây giờ', kind: 'dialect', region: [C, H, Q], ascii: true },
  { from: 'bi nhiêu', to: 'bao nhiêu', kind: 'dialect', region: [S], ascii: true },
  { from: 'bi nhiu', to: 'bao nhiêu', kind: 'dialect', region: [S], ascii: true },
  // ---- single words
  {
    from: 'mô',
    to: 'đâu',
    kind: 'dialect',
    region: [C, H, Q, NT],
    skipIfNext: ['hình', 'tả', 'phỏng', 'tơ', 'đun', 'men', 'típ', 'phạm'],
    skipIfPrev: ['quy', 'vi', 'vĩ', 'niêm'],
    altAfterPrev: {
      prev: [
        ...['khi', 'lúc', 'hồi', 'cái', 'con', 'người', 'bên', 'phía', 'ngày', 'tháng', 'năm', 'lần', 'hôm'],
        ...['bữa', 'bựa', 'giờ', 'chỗ'],
      ],
      to: 'nào',
    },
  },
  {
    from: 'tê',
    to: 'kia',
    kind: 'dialect',
    region: [C, H, Q],
    skipIfNext: ['liệt', 'giác', 'tái', 'buốt', 'cóng', 'dại', 'tê', 'rần', 'bì'],
    skipIfPrev: ['bị', 'gây', 'thuốc', 'đau', 'tê'],
  },
  {
    from: 'răng',
    to: 'sao',
    kind: 'dialect',
    region: [C, H, Q, NT],
    skipIfPrev: ['đánh', 'chải', 'nhổ', 'sâu', 'đau', 'hàm', 'mọc', 'trồng', 'nha', 'cái', 'hàm'],
    skipIfNext: ['miệng', 'cửa', 'hàm', 'khôn', 'sữa', 'nanh', 'giả', 'sâu', 'sún', 'lợi'],
  },
  { from: 'rứa', to: 'vậy', kind: 'dialect', region: [C, H, Q, NT] },
  {
    from: 'chi',
    to: 'gì',
    kind: 'dialect',
    region: [C, H, Q, NT],
    skipIfNext: [
      'phí',
      'tiêu',
      'tiết',
      'nhánh',
      'trả',
      'bộ',
      'đoàn',
      'cục',
      'li',
      'ly',
      'viện',
      'hội',
      'bằng',
      'tộc',
    ],
    skipIfPrev: ['tứ', 'can', 'huống', 'hèn', 'thu', 'kinh', 'ngân'],
  },
  { from: 'ni', to: 'này', kind: 'dialect', region: [C, H, NT], skipIfNext: ['cô', 'sư', 'lông', 'tơ'] },
  { from: 'nớ', to: 'đó', kind: 'dialect', region: [C, H, NT] },
  {
    from: 'ri',
    to: 'thế này',
    kind: 'dialect',
    region: [C, H, NT],
    onlyIfPrev: ['làm', 'như', 'vậy', 'nói'],
  },
  { from: 'ri', to: 'thế này', kind: 'dialect', region: [C, H, NT], onlyLast: true },
  { from: 'chừ', to: 'bây giờ', kind: 'dialect', region: [C, H, Q] },
  { from: 'giừ', to: 'giờ', kind: 'dialect', region: [NT] },
  { from: 'mần', to: 'làm', kind: 'dialect', region: [NT, S] },
  {
    from: 'mạ',
    to: 'mẹ',
    kind: 'dialect',
    region: [C, H, NT],
    skipIfNext: ['vàng', 'bạc', 'kẽm', 'crôm', 'đồng', 'non'],
  },
  { from: 'mệ', to: 'bà', kind: 'dialect', region: [H] },
  // Nghệ Tĩnh "choa" = we / I (not a word of its own anywhere else)
  { from: 'choa', to: 'chúng tôi', kind: 'dialect', region: [NT], ascii: true },
  { from: 'tui', to: 'tôi', kind: 'dialect', region: [S, C], ascii: true },
  { from: 'tau', to: 'tao', kind: 'dialect', region: [C, NT] },
  // without diacritics "tau" is also tàu (train): only as the object of a request or a first word
  {
    from: 'tau',
    to: 'tao',
    kind: 'dialect',
    region: [C, NT],
    ascii: true,
    onlyIfPrev: ['nhắc', 'gọi', 'kêu', 'báo', 'cho', 'với', 'giúp', 'giùm', 'thức', 'làm', ''],
  },
  { from: 'mi', to: 'mày', kind: 'dialect', region: [C, NT], skipIfNext: ['mắt'] },
  {
    from: 'hông',
    to: 'không',
    kind: 'dialect',
    region: [S],
    skipIfPrev: ['bên', 'đau', 'eo', 'xương', 'cạnh', 'mỏi', 'lắc', 'vỗ', 'sườn'],
    skipIfNext: ['xe', 'nhà'],
  },
  { from: 'hổng', to: 'không', kind: 'dialect', region: [S], skipIfPrev: ['lỗ', 'chỗ', 'bị'] },
  { from: 'hem', to: 'không', kind: 'dialect', region: [S], ascii: true },
  { from: 'hơm', to: 'không', kind: 'dialect', region: [S] },
  {
    from: 'hôn',
    to: 'không',
    kind: 'dialect',
    region: [S],
    onlyLast: true,
    skipIfPrev: ['tôi', 'tui', 'mình', 'bạn', 'em', 'anh', 'chị', 'con', 'cháu', 'nó', 'tao', 'mày'],
  },
  ...['dzậy', 'zậy', 'dzị', 'zị', 'dzay', 'zay'].map((f): RewriteEntry => ({
    from: f,
    to: 'vậy',
    kind: 'dialect',
    region: [S],
    ascii: true,
  })),
  ...['dzô', 'zô', 'dzo', 'zo'].map((f): RewriteEntry => ({
    from: f,
    to: 'vào',
    kind: 'dialect',
    region: [S],
    ascii: true,
  })),
  { from: 'dô', to: 'vào', kind: 'dialect', region: [S], skipIfNext: ['ta'] },
  {
    from: 'vô',
    to: 'vào',
    kind: 'dialect',
    region: [S, C],
    onlyIfPrev: ['đi', 'chạy', 'bước', 'nhảy', 'lại', 'bỏ', 'cho', 'đem', 'mang', ''],
    skipIfNext: [
      'lý',
      'cùng',
      'địch',
      'tận',
      'ích',
      'duyên',
      'hạn',
      'số',
      'tình',
      'tư',
      'hình',
      'danh',
      'dụng',
      'nghĩa',
      'giá',
      'biên',
      'cảm',
      'học',
      'ơn',
      'tri',
      'vọng',
      'tuyến',
      'gia',
      'sinh',
      'cơ',
      'hiệu',
      'đây',
    ],
  },
  { from: 'dìa', to: 'về', kind: 'dialect', region: [S] },
  { from: 'quẹo', to: 'rẽ', kind: 'dialect', region: [S], ascii: true },
  {
    from: 'mặt',
    to: 'phải',
    kind: 'dialect',
    region: [S],
    ascii: true,
    onlyIfPrev: ['rẽ', 'quay', 'xoay', 'tay', 'bên', 'phía', 'sang', 'qua'],
    skipIfNext: [
      'trời',
      'trăng',
      'đất',
      'mũi',
      'nạ',
      'lại',
      'sang',
      'qua',
      'về',
      'ra',
      'vào',
      'đi',
      'buồn',
      'vui',
      'giận',
    ],
  },
  {
    from: 'nhiêu',
    to: 'bao nhiêu',
    kind: 'dialect',
    region: [S],
    skipIfPrev: ['bao', 'bấy', 'bây', 'nhiêu'],
  },
  { from: 'trốc', to: 'đầu', kind: 'dialect', region: [NT], ascii: true },
  { from: 'nhởi', to: 'chơi', kind: 'dialect', region: [NT], ascii: true },
  {
    from: 'bổ',
    to: 'ngã',
    kind: 'dialect',
    region: [NT],
    onlyIfNext: ['', 'rồi', 'xuống', 'ngửa', 'sấp', 'nhào', 'lăn', 'đi', 'ra'],
    skipIfPrev: ['thuốc', 'bồi', 'tẩm'],
  },
  { from: 'ngó', to: 'nhìn', kind: 'dialect', region: [C, S], skipIfNext: ['sen'] },
  { from: 'chộ', to: 'thấy', kind: 'dialect', region: [NT] },
  { from: 'nác', to: 'nước', kind: 'dialect', region: [NT] },
  { from: 'ổng', to: 'ông ấy', kind: 'dialect', region: [S] },
  { from: 'bả', to: 'bà ấy', kind: 'dialect', region: [S], skipIfNext: ['chuột', 'vai'] },
  {
    from: 'ảnh',
    to: 'anh ấy',
    kind: 'dialect',
    region: [S],
    skipIfPrev: ['hình', 'chụp', 'bức', 'tấm', 'xem', 'in', 'ghép', 'cái', 'những', 'các'],
    skipIfNext: ['hưởng', 'viện', 'cưới', 'thẻ'],
  },
  { from: 'lẹ', to: 'nhanh', kind: 'dialect', region: [S] },
  { from: 'thiệt', to: 'thật', kind: 'dialect', region: [S], skipIfNext: ['hại', 'thòi', 'mạng'] },
  {
    from: 'coi',
    to: 'xem',
    kind: 'dialect',
    region: [S, C],
    ascii: true,
    skipIfNext: ['chừng', 'như', 'thường', 'trọng', 'sóc', 'bộ'],
    skipIfPrev: ['trông', 'canh'],
  },
  { from: 'bự', to: 'to', kind: 'dialect', region: [S] },
  { from: 'rầu', to: 'buồn', kind: 'dialect', region: [S] },
  { from: 'quạu', to: 'giận', kind: 'dialect', region: [S], ascii: true },
  { from: 'giỡn', to: 'đùa', kind: 'dialect', region: [S] },
  {
    from: 'cấy',
    to: 'cái',
    kind: 'dialect',
    region: [NT],
    onlyIfNext: ['ni', 'nớ', 'tê', 'mô', 'này', 'đó', 'kia', 'gì', 'chi', 'đèn', 'quạt'],
  },
  {
    from: 'nỏ',
    to: 'không',
    kind: 'dialect',
    region: [NT],
    notLast: true,
    skipIfPrev: ['cây', 'bắn', 'cái'],
  },
  ...['dzui', 'zui'].map((f): RewriteEntry => ({
    from: f,
    to: 'vui',
    kind: 'dialect',
    region: [S],
    ascii: true,
  })),
  {
    from: 'ghê',
    to: 'quá',
    kind: 'dialect',
    region: [S],
    onlyLast: true,
    onlyIfPrev: [
      'nóng',
      'lạnh',
      'nực',
      'tối',
      'sáng',
      'chói',
      'rét',
      'oi',
      'giỏi',
      'hay',
      'đẹp',
      'buồn',
      'vui',
      'mệt',
    ],
  },
  {
    from: 'dữ',
    to: 'quá',
    kind: 'dialect',
    region: [S],
    onlyLast: true,
    onlyIfPrev: [
      'nóng',
      'lạnh',
      'nực',
      'tối',
      'sáng',
      'chói',
      'rét',
      'oi',
      'giỏi',
      'hay',
      'đẹp',
      'buồn',
      'vui',
      'mệt',
    ],
  },
  { from: 'hoài', to: 'mãi', kind: 'dialect', region: [S], ascii: true },
  { from: 'nực', to: 'nóng', kind: 'dialect', region: [S] },

  // ---- no-diacritics spellings of the Central words above, gated by context (checked after the
  // accented entries, which win when the word is typed with its diacritics)
  { from: 'chừ', to: 'bây giờ', kind: 'dialect', region: [C, H, Q], ascii: true, onlyIfNext: ['mấy', 'là'] },
  { from: 'rứa', to: 'vậy', kind: 'dialect', region: [C, H, Q, NT], ascii: true, onlyLast: true },
  {
    from: 'rứa',
    to: 'vậy',
    kind: 'dialect',
    region: [C, H, Q, NT],
    ascii: true,
    onlyIfPrev: ['chi', 'gì', 'răng', 'sao', 'làm', 'là'],
  },
  {
    from: 'mô',
    to: 'đâu',
    kind: 'dialect',
    region: [C, H, Q, NT],
    ascii: true,
    onlyIfPrev: ['ở', 'đi', 'bên', 'phía', 'chỗ', 'nơi', 'về', 'tới', 'đến'],
  },
  {
    from: 'mô',
    to: 'nào',
    kind: 'dialect',
    region: [C, H, Q, NT],
    ascii: true,
    onlyIfPrev: [
      'khi',
      'lúc',
      'hồi',
      'cái',
      'con',
      'người',
      'ngày',
      'tháng',
      'năm',
      'lần',
      'hôm',
      'bữa',
      'bựa',
      'giờ',
    ],
  },
  {
    from: 'mô',
    to: 'đâu',
    kind: 'dialect',
    region: [C, H, Q, NT],
    ascii: true,
    onlyLast: true,
    onlyIfPrev: ['đèn', 'quạt'],
  },
  {
    from: 'chi',
    to: 'gì',
    kind: 'dialect',
    region: [C, H, Q, NT],
    ascii: true,
    onlyIfPrev: [
      'làm',
      'tên',
      'nói',
      'có',
      'cái',
      'là',
      'bật',
      'tắt',
      'muốn',
      'biết',
      'hỏi',
      'kêu',
      'ăn',
      'uống',
      'xem',
      'được',
      'chuyện',
    ],
  },
  {
    from: 'ni',
    to: 'này',
    kind: 'dialect',
    region: [C, H, NT],
    ascii: true,
    onlyIfPrev: [
      'cái',
      'đèn',
      'quạt',
      'năm',
      'tháng',
      'bữa',
      'hôm',
      'ngày',
      'chiều',
      'tối',
      'sáng',
      'tuần',
      'lần',
      'bên',
      'chỗ',
      'người',
      'nhà',
      'cây',
      'con',
    ],
  },
  {
    from: 'nác',
    to: 'nước',
    kind: 'dialect',
    region: [NT],
    ascii: true,
    onlyIfPrev: ['uống', 'ly', 'cốc', 'chén', 'lấy'],
  },
  {
    from: 'mi',
    to: 'mày',
    kind: 'dialect',
    region: [C, NT],
    ascii: true,
    onlyIfPrev: [''],
    skipIfNext: ['tôm', 'gói', 'xào'],
  },
  {
    from: 'mi',
    to: 'mày',
    kind: 'dialect',
    region: [C, NT],
    ascii: true,
    onlyLast: true,
    skipIfPrev: ['ăn', 'nấu', 'gói', 'tô', 'bát', 'mua', 'sợi', 'bánh'],
  },
  {
    from: 'răng',
    to: 'sao',
    kind: 'dialect',
    region: [C, H, Q, NT],
    ascii: true,
    onlyIfNext: ['', 'rứa', 'vậy', 'mà', 'không', 'hông', 'mày', 'mi', 'bạn', 'thế', 'chưa'],
    skipIfPrev: ['đánh', 'chải', 'nhổ', 'sâu', 'đau', 'hàm', 'mọc', 'cái', 'cơm', 'xôi'],
  },
  {
    from: 'tê',
    to: 'kia',
    kind: 'dialect',
    region: [C, H, Q],
    ascii: true,
    onlyIfPrev: [
      'đèn',
      'quạt',
      'bên',
      'đằng',
      'cái',
      'ngày',
      'hôm',
      'bựa',
      'phía',
      'nhà',
      'chỗ',
      'cây',
      'người',
    ],
  },
  // Southern "hông" (không) without diacritics: at the end, or before a verb; never the colour
  {
    from: 'hông',
    to: 'không',
    kind: 'dialect',
    region: [S],
    ascii: true,
    onlyLast: true,
    skipIfPrev: [
      'màu',
      'đèn',
      'bên',
      'đau',
      'lắc',
      'eo',
      'xương',
      'sườn',
      'mỏi',
      'vỗ',
      'cạnh',
      'hoa',
      'má',
      'môi',
    ],
  },
  {
    from: 'hông',
    to: 'không',
    kind: 'dialect',
    region: [S],
    ascii: true,
    onlyIfNext: [
      ...[
        'bật',
        'tắt',
        'mở',
        'nhảy',
        'múa',
        'cần',
        'muốn',
        'phải',
        'biết',
        'có',
        'được',
        'đi',
        'chạy',
        'làm',
      ],
      ...['ngủ', 'nói', 'hát', 'quay', 'vẫy', 'thích', 'sao', 'hiểu', 'nghe', 'thấy', 'chịu', 'ăn', 'uống'],
    ],
    skipIfPrev: [
      'màu',
      'đèn',
      'bên',
      'đau',
      'lắc',
      'eo',
      'xương',
      'sườn',
      'mỏi',
      'vỗ',
      'cạnh',
      'hoa',
      'má',
      'môi',
    ],
  },
  {
    from: 'dìa',
    to: 'về',
    kind: 'dialect',
    region: [S],
    ascii: true,
    onlyIfNext: ['chỗ', 'nhà', 'đây', 'đi', 'đó', ''],
  },
  { from: 'dìa', to: 'về', kind: 'dialect', region: [S], ascii: true, onlyIfPrev: ['đi', 'chạy', 'quay'] },
  {
    from: 'mần',
    to: 'làm',
    kind: 'dialect',
    region: [NT, S],
    ascii: true,
    onlyIfNext: ['ơn', 'gì', 'chi', 'được', 'việc', 'sao'],
  },
  {
    from: 'nhiêu',
    to: 'bao nhiêu',
    kind: 'dialect',
    region: [S],
    ascii: true,
    onlyIfPrev: ['còn', 'được', 'là', 'bằng'],
  },
  // Southern pronunciation spellings (gi → d, v → d/z, -iêu → -iu, -ươi → -ừi, qu → w, r → g)
  {
    from: 'dì',
    to: 'gì',
    kind: 'dialect',
    region: [S],
    onlyIfPrev: ['tên', 'làm', 'nói', 'cái', 'là', 'được', 'có', 'chuyện', 'biết'],
  },
  { from: 'dợ', to: 'vậy', kind: 'dialect', region: [S], onlyLast: true },
  { from: 'dị', to: 'vậy', kind: 'dialect', region: [S], onlyLast: true, skipIfPrev: ['kỳ', 'quái', 'dị'] },
  {
    from: 'nhiu',
    to: 'nhiêu',
    kind: 'dialect',
    region: [S],
    ascii: true,
    onlyIfPrev: ['bao', 'bằng', 'là', 'giá', 'còn'],
  },
  { from: 'nhiu', to: 'nhiều', kind: 'dialect', region: [S], ascii: true },
  { from: 'nhìu', to: 'nhiều', kind: 'dialect', region: [S] },
  { from: 'dề', to: 'về', kind: 'dialect', region: [S] },
  { from: 'zề', to: 'về', kind: 'dialect', region: [S] },
  { from: 'dới', to: 'với', kind: 'dialect', region: [S] },
  { from: 'cừi', to: 'cười', kind: 'dialect', region: [S] },
  { from: 'chiện', to: 'chuyện', kind: 'dialect', region: [S] },
  { from: 'wẹo', to: 'rẽ', kind: 'dialect', region: [S], ascii: true },
  {
    from: 'gồi',
    to: 'ngồi',
    kind: 'dialect',
    region: [S],
    onlyIfNext: ['xuống', 'yên', 'dậy', 'đây', 'nghỉ'],
  },
  { from: 'gồi', to: 'rồi', kind: 'dialect', region: [S] },
  { from: 'kêu', to: 'gọi', kind: 'dialect', region: [S, C], onlyIfNext: ['điện'] },
  // Central kinship vocatives and particles at the end of a request ("bật đèn lên đi o")
  { from: 'bọ', to: 'bố', kind: 'dialect', region: [NT], skipIfPrev: ['con', 'cái', 'sâu'] },
  { from: 'o', to: 'cô', kind: 'dialect', region: [C, H], onlyIfNext: ['', 'ơi', 'lan', 'hoa'] },
  { from: 'ôn', to: 'ông', kind: 'dialect', region: [H, C], onlyLast: true },
  { from: 'ôn', to: 'ông', kind: 'dialect', region: [H, C], onlyIfNext: ['ơi'] },
  { from: 'ả', to: 'chị', kind: 'dialect', region: [Q], onlyLast: true },
  { from: 'hí', to: 'hỉ', kind: 'dialect', region: [Q], onlyLast: true },
  { from: 'chơ', to: 'chứ', kind: 'dialect', region: [H], onlyLast: true },
  { from: 'nì', to: 'này', kind: 'dialect', region: [H, NT] },
  { from: 'nì', to: 'này', kind: 'dialect', region: [H, NT], ascii: true, onlyLast: true },
  // Quảng Nam / Bình Định vowels (ươ → ư, uô → u, iê → i, ưa → ơ, a → o, ăn → eng), ASR "mời" for mười
  { from: 'mừi', to: 'mười', kind: 'dialect', region: [Q, C] },
  { from: 'mưi', to: 'mươi', kind: 'dialect', region: [Q, C] },
  {
    from: 'mời',
    to: 'mười',
    kind: 'phonetic',
    region: [C],
    onlyIfNext: ['phút', 'giây', 'lần', 'bước', 'tiếng', 'giờ', 'cái', 'vòng', 'phát', 'lăm', 'mốt'],
    skipIfPrev: ['xin', 'lời'],
  },
  {
    from: 'tóm',
    to: 'tám',
    kind: 'dialect',
    region: [Q],
    onlyIfNext: ['phút', 'giây', 'lần', 'bước', 'tiếng', 'giờ', 'cái', 'vòng', 'phát', 'lăm', 'mốt'],
  },
  {
    from: 'nôm',
    to: 'năm',
    kind: 'dialect',
    region: [Q],
    onlyIfNext: ['phút', 'giây', 'lần', 'bước', 'tiếng', 'giờ', 'cái', 'vòng', 'phát', 'lăm', 'mốt'],
  },
  {
    from: 'úng',
    to: 'uống',
    kind: 'dialect',
    region: [Q],
    onlyIfNext: ['thuốc', 'thúc', 'nước', 'nác', 'trà', 'sữa'],
  },
  { from: 'thúc', to: 'thuốc', kind: 'dialect', region: [Q], onlyIfPrev: ['uống', 'úng', 'viên', 'liều'] },
  { from: 'tíng', to: 'tiếng', kind: 'dialect', region: [Q], onlyIfNext: ['anh', 'việt', 'đồng'] },
  { from: 'tít', to: 'tiết', kind: 'dialect', region: [Q], onlyIfPrev: ['thời'] },
  { from: 'bít', to: 'biết', kind: 'dialect', region: [Q], skipIfPrev: ['đóng', 'lấp'] },
  {
    from: 'mơ',
    to: 'mưa',
    kind: 'dialect',
    region: [Q],
    onlyIfPrev: ['có', 'trời', 'bị', 'mắc', 'dính', 'đang'],
  },
  {
    from: 'lòm',
    to: 'làm',
    kind: 'dialect',
    region: [Q],
    onlyIfNext: ['chi', 'gì', 'được', 'việc', 'sao', 'ơn'],
  },
  {
    from: 'eng',
    to: 'ăn',
    kind: 'dialect',
    region: [Q],
    onlyIfNext: [
      'cơm',
      'chuối',
      'phở',
      'bún',
      'cháo',
      'bánh',
      'kẹo',
      'kem',
      'xôi',
      'mì',
      'trái',
      'quả',
      'gì',
      'chi',
      'táo',
      'thịt',
      'cá',
    ],
  },
  { from: 'eng', to: 'anh', kind: 'dialect', region: [NT] },
]
