/**
 * Function words (spec §2 N12). Fillers are tagged in the DP at a very low weight, so any real
 * phrase beats them ("xin chào" is a greeting, not "xin" + "chào"). "Strong" fillers are phrases that
 * must beat a concept word they contain ("trời ơi" is not weather, "phải không" is not "right").
 */

export const FILLERS = [
  // politeness / imperative
  'hãy',
  'xin',
  'xin mời',
  'mời',
  'giúp',
  'giùm',
  'dùm',
  'hộ',
  'giúp tôi|mình|tui|em|con|cháu|với|tớ',
  'giùm tôi|tui|cái|mình|em|con|cháu',
  'dùm tôi|tui|mình|cái',
  // wrappers
  'cho tôi|tui|mình|em|con|cháu|tao|bà|ông|tớ [xem|coi|nghe|biết|hỏi]',
  'tôi|tui|mình|em|con|cháu muốn [bạn|xem]',
  'tôi|tui|mình cần',
  'bạn có thể [nào]',
  'có thể',
  'có được không',
  'được không',
  'được hông',
  'được chứ',
  'bạn có biết',
  'biết không',
  'cho hỏi',
  'nói cho tôi|tui|mình biết',
  'nói tôi|tui|mình nghe',
  'thử xem',
  'coi thử',
  'cho',
  'được',
  'biết',
  'muốn',
  'cần',
  'có',
  'làm',
  // immediacy / softeners
  'ngay',
  'bây giờ',
  'giờ',
  'liền',
  'luôn',
  'nhanh lên',
  'lẹ lên',
  'một chút',
  'lát nữa',
  'một lát',
  'chút nữa',
  'tí nữa',
  'chút',
  'chút xíu',
  'một tí',
  'tí',
  'xíu',
  'đã',
  'lên',
  'xuống',
  'ra',
  'vào',
  'đây',
  'kia',
  'nữa',
  'lại',
  'đi',
  'thôi',
  'với',
  'cái',
  'rồi',
  'xong',
  'đâu',
  'đến',
  'tới',
  'sau',
  'trong',
  'hiện tại',
  'hiện giờ',
  'lúc này',
  'năm nay',
  'tháng này',
  'tháng sau',
  'tháng tới',
  'tuần này',
  // discourse
  'thì',
  'mà',
  'là',
  'vậy',
  'thế',
  'đó',
  'đấy',
  'kìa',
  'cũng',
  'chắc',
  'hình như',
  'và',
  'hay',
  'hoặc',
  'nhưng',
  'quá',
  'lắm',
  'rất',
  'hơi',
  'thật',
  'đang',
  'sẽ',
  'vừa',
  'mới',
  'của',
  'này',
  'nào',
  'ấy',
  'để',
  'như',
  'thấy',
  'cảm thấy',
  'hết',
  'nhiều',
  'ở',
  'tại',
  'ngoài',
  'dưới',
  'trên',
  'bên',
  'tỉnh',
  'thành phố',
  'tp',
  'miền',
  'khu vực',
  'vùng',
  // pronouns
  'tôi',
  'tui',
  'tao',
  'tớ',
  'mình',
  'bạn',
  'cậu',
  'mày',
  'em',
  'anh',
  'chị',
  'con',
  'cháu',
  'ông',
  'bà',
  'cô',
  'chú',
  'bác',
  'robot',
  'người máy',
  'nó',
  'chúng ta',
  'chúng mình',
  'chúng tôi',
  'mọi người',
  'ronaldo',
  'ông ấy',
  'bà ấy',
  'anh ấy',
  'cả nhà',
  'các bạn',
  'người',
  // particles
  'nhé',
  'nhe',
  'nha',
  'nhá',
  'nhen',
  'nghen',
  'nghe',
  'ha',
  'hả',
  'hở',
  'hén',
  'hen',
  'hỉ',
  'hè',
  'nhỉ',
  'ạ',
  'à',
  'ư',
  'á',
  'ta',
  'chứ',
  'thử',
  'xem',
  'coi',
  'rứa',
  'tề',
  'ok',
  'ừ',
  'ừm',
  'ờ',
  'dạ',
  'vâng',
  'yes',
] as const

export const STRONG_FILLERS = [
  // vocatives: "<name> ơi" (critique: the bot name is a vocative too)
  'bạn|robot|ronaldo|ba|bố|mẹ|má|mạ|tía|trời|con|cháu|em|anh|chị|ông|bà|cô|chú|bác|cưng|bé|nè|o|ôn|mệ|bọ|eng|ả|bọn|bây ơi',
  'người máy ơi',
  'cả nhà ơi',
  'mọi người ơi',
  'ơi',
  'ê',
  'hey',
  'nè',
  'này bạn',
  'ronaldo',
  // multi-word fillers that contain a concept word ("vui lòng" is not "vui", "lập tức" not "tức")
  'làm ơn',
  'mần ơn',
  'vui lòng',
  'lập tức',
  'ngay lập tức',
  'ngay bây giờ',
  'chèn ơi',
  'chèn đét ơi',
  'mèn ơi',
  'mèn đét ơi',
  'trời đất ơi',
  'trời đất',
  'trời ơi đất hỡi',
  'quá trời quá đất',
  'ối trời ơi',
  'trời đất quỷ thần ơi',
  // compounds whose single words are concepts ("tin tức" is news, not "tức" = angry)
  { p: 'tin tức', weight: 1.5 },
  { p: 'máy bay', weight: 1.5 },
  { p: 'mắt kém', weight: 1.5 },
  'dạo này',
  'đầu tiên',
  'cuối cùng',
  // question tags that contain a concept word
  'có phải',
  'phải không',
  'phải rồi',
  'không phải',
  'đúng không',
  'đúng rồi',
  'đúng vậy',
  'phải vậy không',
] as const

/**
 * Everyday words that are complete without diacritics. Typed so inside accented text they are
 * read as typed (tim = heart, lan = orchid / a name, trai = boy), not as tím / lặn / trái.
 */
export const COMMON_ASCII_WORDS = [
  'tim',
  'lan',
  'trai',
  're',
  'tam',
  'tu',
  'le',
  'linh',
  'xe',
  'hoa',
  'nha',
  'tay',
  'chan',
  'an',
  'vang',
  'dan',
  'com',
  'canh',
  'tien',
  'thu',
  'tho',
  'kho',
] as const

/**
 * Common words written without a tone mark that also exist with one in the lexicon: typed so,
 * they are taken as typed (đầu tiên, mây, mùa đông), not as tiến / mấy / đóng.
 */
export const COMMON_LEVEL_WORDS = [
  ...['tiên', 'mây', 'đông', 'lăn', 'cân', 'thân', 'bưng', 'buông', 'chuyên', 'châm', 'căn', 'cơ'],
  ...['cưa', 'dân', 'dâu', 'dây', 'dê', 'dơ', 'dư', 'dưng', 'gân', 'hiên', 'hô', 'hơ', 'hương', 'kê'],
  ...['lân', 'lăng', 'muôn', 'mơ', 'ngôi', 'ngơ', 'ngươi', 'nhăn', 'nôi', 'quân', 'quây', 'săm'],
  ...['thăng', 'thưa', 'tiêu', 'tê', 'tơ', 'trông', 'trơ', 'vây', 'xâu', 'ôn', 'đan', 'đinh', 'đêm'],
  ...['đâm', 'đê', 'đua', 'đu', 'đăng', 'đôi', 'ơ', 'ây', 'chê', 'hôi', 'lây', 'tăm', 'bô', 'chơ'],
] as const

/** Trailing particles stripped unconditionally from the end of a clause (spec §2 trailing-particle pass). */
export const TRAILING_PARTICLES = [
  'nhé',
  'nhe',
  'nha',
  'nhá',
  'nhen',
  'nghen',
  'nghe',
  'ha',
  'hả',
  'hở',
  'hén',
  'hen',
  'hỉ',
  'hè',
  'nhỉ',
  'ạ',
  'à',
  'ư',
  'á',
  'ta',
  'chứ',
  'đó',
  'đấy',
  'luôn',
  'liền',
  'thử',
  'xem',
  'coi',
  'nào',
  'vậy',
  'thế',
  'rứa',
  'kìa',
  // Huế "tề" ≈ kìa
  'tề',
  'nè',
  'ơi',
  'này',
  'ok',
  // a trailing addressee: "nhảy đi bạn", "bật quạt giùm tui"
  'bạn',
  'robot',
  'ronaldo',
  'em',
  'con',
  'cháu',
  'anh',
  'chị',
  'ông',
  'bà',
  'cô',
  'chú',
  'bác',
  'mày',
  'tôi',
  'tui',
  'tao',
  'tớ',
  'mình',
  'giùm',
  'dùm',
  'hộ',
  // Central / Southern addressees and particles ("bật đèn lên đi o", "mấy giờ rồi hỉ")
  'bố',
  'mẹ',
  'o',
  'ả',
  'bọn',
  'bây',
  'đa',
  'mà',
  'tía',
  'má',
  'hầy',
  'nờ',
] as const

/** Stripped from the end only when the guards hold (see clauses.ts). */
export const CONDITIONAL_PARTICLES = [
  'đi',
  'thôi',
  'với',
  'cái',
  'lại',
  'rồi',
  'nữa',
  'đâu',
  'không',
  'hông',
  'chưa',
  'xong',
  'lên',
  'xuống',
] as const

/** Stripping one of these from the end marks the clause as a question. */
export const QUESTION_PARTICLES = ['không', 'hông', 'chưa', 'hả', 'hở', 'à', 'ư', 'nhỉ', 'chứ'] as const

/** "tôi buồn quá": a first-person subject turns an emotion into small talk about the user. */
export const USER_PRONOUNS = ['tôi', 'tui', 'tao', 'tớ', 'mình', 'em', 'con', 'cháu', 'bà', 'ông'] as const

/** Words allowed between the user pronoun and the emotion word. */
export const SUBJECT_BRIDGES = [
  'đang',
  'thấy',
  'cảm thấy',
  'hơi',
  'rất',
  'thật',
  'cũng',
  'bị',
  'hôm nay',
  'nay',
] as const

/** Words that do not make a following "rồi"/"xong" a clause separator. */
export const LIGHT_WORDS = [
  ...TRAILING_PARTICLES,
  'không',
  'hông',
  'chưa',
  'sao',
  'đâu',
  'mà',
  'hả',
  'hở',
] as const
